services:
  mongodb:
    image: mongo:7.0
    container_name: pebble-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=pebble-sales-hub
    command: [ "--replSet", "rs0", "--bind_ip_all" ]

volumes:
  mongodb_data:
